name: E2E Tests
on:
  # Run on any commit to the #master branch
  push:
    branches: [master, develop]
  # Run on pull requests into the #master branch
  pull_request:
    branches: [master, develop]
jobs:
  cypress-test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CYPRESS_RESPONSE_TIMEOUT: 200000
      CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
      CYPRESS_RETRIES: 2
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: ab_service_bot_manager
      - name: Install AppBuilder
        uses: digi-serve/ab-install-action@v1
      - name: Check out kitchen-sink tests
        uses: actions/checkout@v2
        with:
          repository: digi-serve/kitchensink_app
          path: AppBuilder/test/e2e/cypress/e2e/kitchensink_app
      - name: Wait for AB
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:80
          timeout: 300000
      - name: Run Cypress Tests
        run: npm run test:e2e:app -- --browser chrome
        working-directory: ./AppBuilder
      - name: Save Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./AppBuilder/test/e2e/cypress/screenshots
